services:
  - type: web
    name: disease-predictor
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: API_KEY
        value: q9o3wef9U3nf983nNef923nfENf9WEn
